language: python
python: 2.7
install:
- mkdir -p buildout-cache/downloads
- python bootstrap.py
- bin/buildout -N -q
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: bin/code-analysis && bin/test
after_success:
- bin/coverage.sh
- pip install coverage==3.7 coveralls
- coveralls
after_failure:
- bin/buildout annotate
- firefox -v
